name = "Winter Modpack"
author = "nicoladen05"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ff867342af046b9a00c60e80744c721cc720cad85de228d3b35976892704b21"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
