name = "Winter Modpack"
author = "nicoladen05"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62c631cc1206ba620980032d9f63d626aa7d462766957204a48ae1335e294cb2"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
