name = "Winter Modpack"
author = "nicoladen05"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5fc12c5ad46e62be2de24d9f1dd74c2fdced8acb53a14a19a7f1bef1f38ce14"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
