name = "Winter Modpack"
author = "nicoladen05"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ca9b858a60aa0a187ee4f293a24b6513f9ad5530b8c32b1833d457a6d9c4a34"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
