name = "Winter Modpack"
author = "nicoladen05"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "131a49a89c4718c65caf0d2034e94a2d0dc1d963c3894d0ef99cba1fa4887fd6"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
